apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: Group
metadata:
  labels:
    app.kubernetes.io/name: usernaut
    app.kubernetes.io/managed-by: kustomize
  name: dataverse-aggregate-mygroup
  namespace: usernaut
spec:
  # This is the LDAP group name that will be synced
  group_name: dataverse-platform-atlan-test
  members:
   users:
    - subhatta
    - vinod
  group_params:
    - backend: gitlab
      name: gitlab
      property: project_access_paths
      value:
        - dataverse/datavers-config/dataproduct-config
        - dataverse/astro/astro-toolkit
        - dataverse/platform-tooling/fivetran_terraform
  backends:
    - name: rover
      type: rover
    - name: atlan
      type: atlan


  