apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: Group
metadata:
  labels:
    app.kubernetes.io/name: usernaut
    app.kubernetes.io/managed-by: kustomize
  name: dataverse-aggregate-mygroupquerybased
  namespace: usernaut
spec:
  group_name: dataverse-aggregate-mygroupquerybased
  query: (&(manager=uid=pbhattac,ou=users,dc=redhat,dc=com)(&(title=*senior*)))
  members:
   users:
    - subhatta
    - vinod
  backends:
  - name: snowflake
    type: snowflake
